--DROP TABLE IF EXISTS mpas, films, genres, films_genres, users, films_likes, friendships;

CREATE TABLE IF NOT EXISTS mpas (
    mpa_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
    film_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(64) NOT NULL,
    description varchar(200),
    release_date date NOT NULL,
    duration INTEGER,
    mpa_id SMALLINT REFERENCES mpas (mpa_id)
);

CREATE TABLE IF NOT EXISTS genres (
    genre_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS films_genres (
    genre_id SMALLINT NOT NULL REFERENCES genres (genre_id) ON DELETE CASCADE,
    film_id BIGINT NOT NULL REFERENCES films (film_id) ON DELETE CASCADE,
    PRIMARY KEY (genre_id, film_id)
);


CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(32) NOT NULL,
    login varchar(20) NOT NULL,
    name varchar(64) NOT NULL,
    birthday date
);

CREATE TABLE IF NOT EXISTS films_likes (
    user_id BIGINT NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
    film_id BIGINT NOT NULL REFERENCES films (film_id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, film_id)
);

CREATE TABLE IF NOT EXISTS friendships (
    user_id BIGINT NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
    friend_id BIGINT NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
    status BOOLEAN NOT NULL,
    PRIMARY KEY (user_id, friend_id)
);
